# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1It8nMnr1gVRoVhOxveExQ8-HYHcErXpd
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import bernoulli
# no of simulations
simlen=int(1e5)
# Probability of rv X in range(-1,0)
prob1= 1/2
# Probability of rv Y in range(-2,-1)
prob2= 1/3
# Probability of rv Z in range(-3,-2)
prob3=  (1/2) * prob1 * prob2

#Simulations using Bernoulli r.v.
data_bern = bernoulli.rvs(size=simlen,p=prob3)

#Calculating the number of favourable outcomes
err_ind = np.nonzero(data_bern == 1)

#calculating the simulated probability
sim_prob = np.size(err_ind)/simlen

#Theory vs simulation
print("The simulated prob is",sim_prob)
print("The theoretical prob is",prob3)

sim_list= [0,sim_prob,0]
theory_list=[0,prob3,0]
# RV X=1 for Z<= 2
# plotting
X = np.arange(3)
fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
plt.xlabel('Random variable, X')
plt.ylabel('Probability, $P_{r}(Z)$')
ax.bar(X - 0.125, sim_list, color = 'b', width = 0.25)
ax.bar(X + 0.125, theory_list, color = 'r', width = 0.25)
plt.title('Probability distribution')
ax.legend(labels=['Simulation', 'Analysis'])
plt.grid()