# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1It8nMnr1gVRoVhOxveExQ8-HYHcErXpd
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import bernoulli
# no of simulations
simlen=int(1e5)
# Probability of rv Z in range(-3,-2)
prob=  1/12

#Simulations using Bernoulli r.v.
data_bern = bernoulli.rvs(size=simlen,p=prob)

#Calculating the number of favourable outcomes
err_ind = np.nonzero(data_bern == 1)

#calculating the simulated probability
sim_prob = np.size(err_ind)/simlen

#Theory vs simulation
print("The simulated prob is",sim_prob)
print("The theoretical prob is",prob)


# plotting
sim_list= [0,0,sim_prob]
theory_list=[0,0,prob]
X = np.arange(3)
fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
positions = ( 0, 1,2)
labels = ("-4","-3", "-2")
plt.xticks(positions, labels)
plt.xlabel('Random variable, Z')
plt.ylabel('Probability, $P_{r}(Z)$')
ax.bar(X - 0.75, sim_list, color = 'b', width = 0.5)
ax.bar(X - 0.25, theory_list, color = 'r', width = 0.5)
ax.legend(labels=['Simulation', 'Analysis'])
plt.grid()
