# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1It8nMnr1gVRoVhOxveExQ8-HYHcErXpd
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

# For plotting the  marginal PDF of X
# Setting the corresponding x and y - coordinates
# Region 1 of PDF
x_1 = np.arange(-1, 0, 0.01)
y_1 = x_1*0
# Region 2 of PDF
x_2 =   np.arange(0, 1, 0.01)
y_2=  4*x_2*(1- x_2**2)
# Region 3 of PDF
x_3 =   np.arange(1, 2, 0.01)
y_3=  x_3*0

# Plotting the points
plt.plot(x_1, y_1,'b')
plt.plot(x_2, y_2,'b')
plt.plot(x_3, y_3,'b')
plt.xlabel('Random Variable , X')
plt.ylabel('$f_{X}(x)$')

# function to show the plot
plt.grid()
plt.show()
# For plotting the  marginal PDF of Y
# Setting the corresponding x and y - coordinates
# Region 1 of PDF
x_4 = np.arange(-1, 0, 0.01)
y_4 = x_4*0
# Region 2 of PDF
x_5 =   np.arange(0, 1, 0.01)
y_5=  4*( x_5**3)
# Region 3 of PDF
x_6 =   np.arange(1, 2, 0.01)
y_6=  x_6*0

# Plotting the points
plt.plot(x_4, y_4,'b')
plt.plot(x_5, y_5,'b')
plt.plot(x_6, y_6,'b')
plt.xlabel('Random Variable , Y')
plt.ylabel('$f_{Y}(y)$')


# function to show the plot
plt.grid()
plt.show()

# For plotting of marginal CDF of X
# Setting the corresponding x and y - coordinates
# Region 1 of PDF
x_4 = np.arange(-1, 0, 0.01)
y_4 = x_4*0
# Region 2 of PDF
x_5 =   np.arange(0, 1, 0.01)
y_5=  2*x_5**2 - x_5**4
# Region 3 of PDF
x_6 =   np.arange(1, 2, 0.01)
y_6=  x_6**0

# Plotting the points
plt.plot(x_4, y_4,'b')
plt.plot(x_5, y_5,'b')
plt.plot(x_6, y_6,'b')
plt.xlabel('Random Variable , X')
plt.ylabel('$F_{X}(x)$')


# function to show the plot
plt.grid()
plt.show()