# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1It8nMnr1gVRoVhOxveExQ8-HYHcErXpd
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import bernoulli

# For plotting the PDF of X
# Setting the corresponding x and y - coordinates
# Region 1 of PDF
x_1 = np.arange(-1, 0, 0.01)
y_1 = x_1*0
# Region 2 of PDF
x_2 =   np.arange(0, 1, 0.01)
y_2=  (3*(1-x_2)*(9 - x_2))/13
# Region 3 of PDF
x_3 =   np.arange(1, 2, 0.01)
y_3=  x_3*0

# Plotting the points
plt.plot(x_1, y_1,'b')
plt.plot(x_2, y_2,'b')
plt.plot(x_3, y_3,'b')
plt.xlabel('Random Variable , X')
plt.ylabel('$Pr(x)$')

# function to show the plot
plt.grid()
plt.show()